### ISSUE TITLE
Add contracts

### ISSUE THREAD

**Issue by rfdonnelly** [rfdonnelly/jobrnr#5]
For method type checking.

https://github.com/egonSchiele/contracts.ruby

**Comment by rfdonnelly** [comment]
Blocked by https://github.com/egonSchiele/contracts.ruby/pull/214

**Comment by rfdonnelly** [comment]
Passing string to job::repeat results in obtuse error message.  Add contracts where possible to catch this issue earlier and give better guidance.

Example job description:
```ruby
job :example do
   execute 'sleep 1'
   repeat '50'
end
```

Error message:
```text
jobrnr/lib/jobrnr/stats.rb:30:in `+': String can't be coerced into Fixnum (TypeError)
        from jobrnr/lib/jobrnr/stats.rb:30:in `each'
        from jobrnr/lib/jobrnr/stats.rb:30:in `reduce'
        from jobrnr/lib/jobrnr/stats.rb:30:in `queue'
```

**Comment by rfdonnelly** [comment]
From 666e60e:

Tried [contracts.ruby](https://github.com/egonSchiele/contracts.ruby) but does not allow mixing of default values and blocks (see [contracts.ruby/214](egonSchiele/contracts.ruby#214)).  Additionally, contracts.ruby gives developer friendly messages but does not give user friendly messages.

Instead, rolled my own argument validation.  Error messages include expected type, actual value, actual type, and source location.

**Comment by rfdonnelly** [comment]
Won't add contracts due to:

* Non-user-friendly error messages
* Blocker (above)

Instead, implement custom argument validation.  See issue #31.
